sudo: required
dist: trusty
language: node_js
node_js:
  - "5.1"

install:
  - npm install -g gulp eslint
  - npm install
  - pushd qmlify
  - npm install
  - popd
  - pushd quickly
  - npm install
  - popd
  - sudo add-apt-repository -y ppa:beineri/opt-qt551-trusty
  - sudo add-apt-repository -y ppa:beineri/opt-qt56-trusty
  - sudo apt-get update
  - sudo apt-get -y install qt55declarative qt55tools
  - sudo apt-get -y install qt56declarative qt56tools
  - sudo apt-get -y install xvfb

script:
  - pushd qmlify
  - gulp
  - npm test
  - npm link
  - popd
  - pushd quickly

  - source /opt/qt55/bin/qt55-env.sh
  - mkdir build; pushd build
  - qmake .. && make && sudo make install
  - popd
  - xvfb-run -a -s "-screen 0 800x600x24" npm run test

  - source /opt/qt56/bin/qt56-env.sh
  - rm -r build/*; pushd build
  - qmake .. && make && sudo make install
  - popd
  - xvfb-run -a -s "-screen 0 800x600x24" npm run test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/837b6cbd8f8ea536e8a6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
